### ISSUE TITLE
Update Helm Charts to Match the Most Recent Version of Perses

### ISSUE THREAD

**Issue by rasmusvan** [perses/helm-charts#15]
### Proposal

Using Perses to embed Panels and Dashboards is difficult, when the version on localhost:8080 is different from the one in my application. It makes sense to run the newest release instead of the one from 8 months ago

**Comment by Nexucis** [comment]
yes you are right, that doesn't make sense. The helm chart should always be sync with the latest version.

Unfortunately the helm chart is not well maintained. If someone would like to help us on this area, that would be great.

**Comment by Nexucis** [comment]
should be good now @rasmusvan thanks to the work from @indigo423
